# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

# Copy the whole monorepo
COPY . .

# Install all dependencies (monorepo-aware)
RUN npm install

# Build just this service
RUN npm run build auth-service
# Stage 2: Runtime
FROM node:18-alpine

WORKDIR /app

# Copy built files only for this service
COPY --from=builder /app/dist/apps/auth-service /app/dist/apps/auth-service
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

ENV NODE_ENV=production



CMD ["node", "dist/apps/auth-service/main"]
